### ISSUE TITLE
Build error on Google App Engine

### ISSUE THREAD

**Issue by sublee** [ikawaha/kagome#124]
Thank you for the great library. It is perfect to solve my challenge.

When I build a GAE app which depends on `kagome`, it was failed with `newContents` redeclaration error:

```
kagome/internal/dic/content_appengine.go:23:32: newContents redeclared in this block
```

Because both `content.go` and `content_appengine.go` declares `newContents` with the `appengine` build tag.

I guess there's no reason to separate `content_appengine.go` anymore since this commit: https://github.com/ikawaha/kagome/commit/597ca21f4206000db2e69a94f0a08fa280254a9d.

**Comment by ikawaha** [comment]
Thanks for the bug report! Your issue should be fixed by the commit above.

**Comment by sublee** [comment]
My issue is fixed! Thank you!
