### ISSUE TITLE
[Question] Comparison to other morphological analyzers

### ISSUE THREAD

**Issue by CaptainDario** [ikawaha/kagome#264]
I am very interested in this project and consider incorporating it into my application.

I am not sure if this is the right place to ask, but I am curious how this compares to other morphological analyzers like MeCab JUMAN++. Do you have any comparisons or know of some?

**Comment by ikawaha** [comment]
Hi,

kagome is a MeCab clone and also uses the MeCab dictionary (IPADic/UniDic).
Parsing results of kagome are equivalent to those of MeCab, but there may be a slight difference in the analysis of unknown words.

The following is a system diagram of Japanese morphological analyzers.
I hope it will be of some help.

![image](https://user-images.githubusercontent.com/4232165/154178154-a405b8e3-e25e-415f-ac49-54a6202ad933.png)
