### ISSUE TITLE
proposal: fluent accesibility for features

### ISSUE THREAD

**Issue by suzuken** [ikawaha/kagome#70]
Thank you for providing useful library. I want more fluent accessibility to `Token` attributes to simplify the workflow.

For example:

```go
func main() {
	t := tokenizer.New()
	tokens := t.Tokenize("寿司が食べたい。")
	for _, token := range tokens {
		if token.Class == tokenizer.DUMMY {
			continue
		}
		if len(token.Features()) >= 1 && token.Features()[0] == "名詞" {
			fmt.Printf("%v\n", token)
		}
	}
}
```

if `Token.Pos()` is implemented, do like that:

```go
func main() {
	t := tokenizer.New()
	tokens := t.Tokenize("寿司が食べたい。")
	for _, token := range tokens {
		// interface to access Pos, Yomi, or etc..
		if token.Features().Pos() == "名詞" {
			// ...
		}

		// or simply
		if token.Pos() == "名詞" {
			// ...
		}
	}
}

```

How about providing `Pos() string`, `Token() []string` etc. on `Token`?  `Token.Features() []string` should provide features on any dictionary classes, so is it difficult to provide that interface? ( I'm not familiar with Morphological Analyzer, so I'm not certain that it's enable to deal features by the same way UserDic, SysDic, and Unknown. )

**Comment by ikawaha** [comment]
Thank you for your proposal.
I think so. :+1:

**Comment by suzuken** [comment]
Thank you for your reply! I'll make PR later.

**Comment by suzuken** [comment]
oh, already https://github.com/ikawaha/kagome/pull/71 . Thanks! :)

**Comment by ikawaha** [comment]
FYI: http://ikawaha.hateblo.jp/entry/2016/03/18/110442
