### ISSUE TITLE
Too much memory allocation in CommonPrefixSearch

### ISSUE THREAD

**Issue by suzuken** [ikawaha/kagome#75]
Hi @ikawaha san. I try to run kagome on long running purpose, and find some memory allocation in tokenizer.

    -> % go test -v ./tokenizer -run=^$ -bench=. -benchmem -benchtime=2s -memprofile=prof.mem | tee mem.0
    PASS
    BenchmarkAnalyzeNormal-8           20000            140704 ns/op           19179 B/op        581 allocs/op
    BenchmarkAnalyzeSearch-8           20000            185009 ns/op           19178 B/op        581 allocs/op
    BenchmarkAnalyzeExtended-8         20000            180695 ns/op           18240 B/op        582 allocs/op
    ok      github.com/ikawaha/kagome/tokenizer     15.453s

And reading it by pprof

    -> % go tool pprof --alloc_space tokenizer.test prof.mem
    Entering interactive mode (type "help" for commands)
    (pprof) top
    1699.93MB of 1711.81MB total (99.31%)
    Dropped 19 nodes (cum <= 8.56MB)
    Showing top 10 nodes out of 45 (cum >= 14.28MB)
          flat  flat%   sum%        cum   cum%
      796.54MB 46.53% 46.53%  1046.54MB 61.14%  github.com/ikawaha/kagome/internal/dic.IndexTable.CommonPrefixSearch
      406.58MB 23.75% 70.28%  1454.63MB 84.98%  github.com/ikawaha/kagome/tokenizer.Tokenizer.Analyze
         250MB 14.60% 84.89%      250MB 14.60%  github.com/ikawaha/kagome/internal/da.DoubleArray.CommonPrefixSearch
      114.91MB  6.71% 91.60%   114.91MB  6.71%  bytes.makeSlice
       59.99MB  3.50% 95.11%    59.99MB  3.50%  strings.genSplit
          47MB  2.75% 97.85%       47MB  2.75%  encoding/binary.Read
       10.34MB   0.6% 98.46%    31.84MB  1.86%  github.com/ikawaha/kagome/internal/da.Read
        8.98MB  0.52% 98.98%    68.97MB  4.03%  github.com/ikawaha/kagome/internal/dic.NewContents
        3.31MB  0.19% 99.17%    16.81MB  0.98%  github.com/ikawaha/kagome/internal/dic.LoadConnectionTable
        2.28MB  0.13% 99.31%    14.28MB  0.83%  github.com/ikawaha/kagome/internal/dic.LoadMorphSlice

And see allocation in each line.

    (pprof) list CommonPrefixSearch
    Total: 1.67GB
    ROUTINE ======================== github.com/ikawaha/kagome/internal/da.DoubleArray.CommonPrefixSearch in /Users/ke-suzuki/src/github.com/ikawaha/kagome/internal/da/da.go
         250MB      250MB (flat, cum) 14.60% of Total
             .          .    101:           if q >= bufLen || int(d[q].Check) != p {
             .          .    102:                   break
             .          .    103:           }
             .          .    104:           ahead := int(d[q].Base) + int(terminator)
             .          .    105:           if ahead < bufLen && int(d[ahead].Check) == q && int(d[ahead].Base) <= 0 {
         123MB      123MB    106:                   ids = append(ids, int(-d[ahead].Base))
         127MB      127MB    107:                   lens = append(lens, i+1)
             .          .    108:           }
             .          .    109:   }
             .          .    110:   return
             .          .    111:}
             .          .    112:
    ROUTINE ======================== github.com/ikawaha/kagome/internal/dic.IndexTable.CommonPrefixSearch in /Users/ke-suzuki/src/github.com/ikawaha/kagome/internal/dic/index.go
      796.54MB     1.02GB (flat, cum) 61.14% of Total
             .          .     61:}
             .          .     62:
             .          .     63:// CommonPrefixSearch finds keywords sharing common prefix in an input
             .          .     64:// and returns the ids and it's lengths if found.
             .          .     65:func (idx IndexTable) CommonPrefixSearch(input string) (lens []int, ids [][]int) {
             .      250MB     66:   seeds, lens := idx.Da.CommonPrefixSearch(input)
             .          .     67:   for _, id := range seeds {
             .          .     68:           dup, _ := idx.Dup[int32(id)]
      351.02MB   351.02MB     69:           list := make([]int, 1+dup, 1+dup)
             .          .     70:           for i := 0; i < len(list); i++ {
             .          .     71:                   list[i] = id + i
             .          .     72:           }
      445.52MB   445.52MB     73:           ids = append(ids, list)
             .          .     74:   }
             .          .     75:   return
             .          .     76:}
             .          .     77:
             .          .     78:// Search finds the given keyword and returns the id if found.

---

For reducing allocation, it is prefer to use `append` without creating new slice. Do you have any ideas to reduce allocation in `DoubleArray.CommonPrefixSearch` and `IndexTable.CommonPrefixSearch` ? For example,

```go
func (d DoubleArray) CommonPrefixSearch(input string) (ids, lens []int) {
	var p, q int
	bufLen := len(d)
	ids = make([]int, 0, SOME_FIXED_SIZE)
	lens = make([]int, 0, SOME_FIXED_SIZE)
	for i, size := 0, len(input); i < size; i++ {
		p = q
		q = int(d[p].Base) + int(input[i])
		if q >= bufLen || int(d[q].Check) != p {
			break
		}
		ahead := int(d[q].Base) + int(terminator)
		if ahead < bufLen && int(d[ahead].Check) == q && int(d[ahead].Base) <= 0 {
			ids = append(ids, int(-d[ahead].Base))
			lens = append(lens, i+1)
		}
	}
	return
}
```

may be reduce allocation in many cases, but I'm not sure how `SOME_FIXED_SIZE` should be defined.

**Comment by ikawaha** [comment]
:scream: Thank you for your report.

**Comment by ikawaha** [comment]
```
$ go tool pprof --alloc_space tokenizer.test fix_mem.prof
Entering interactive mode (type "help" for commands)
(pprof) top
1020.66MB of 1033.17MB total (98.79%)
Dropped 27 nodes (cum <= 5.17MB)
Showing top 10 nodes out of 44 (cum >= 7.50MB)
      flat  flat%   sum%        cum   cum%
  773.95MB 74.91% 74.91%   775.96MB 75.10%  github.com/ikawaha/kagome/tokenizer.Tokenizer.Analyze
  114.31MB 11.06% 85.97%   114.31MB 11.06%  bytes.makeSlice
   60.99MB  5.90% 91.88%    60.99MB  5.90%  strings.genSplit
   46.50MB  4.50% 96.38%    46.50MB  4.50%  encoding/binary.Read
   10.34MB  1.00% 97.38%    32.84MB  3.18%  github.com/ikawaha/kagome/internal/da.Read
    8.98MB  0.87% 98.25%    69.97MB  6.77%  github.com/ikawaha/kagome/internal/dic.NewContents
    3.31MB  0.32% 98.57%    20.31MB  1.97%  github.com/ikawaha/kagome/internal/dic.LoadConnectionTable
    2.28MB  0.22% 98.79%     9.28MB   0.9%  github.com/ikawaha/kagome/internal/dic.LoadMorphSlice
         0     0% 98.79%   117.31MB 11.35%  bytes.(*Buffer).ReadFrom
         0     0% 98.79%     7.50MB  0.73%  encoding/gob.(*Decoder).Decode
```
