### ISSUE TITLE
Cannot Use in Google App Engine Due to Unsafe Package

### ISSUE THREAD

**Issue by niconegoto** [ikawaha/kagome#86]
I would like to use Goji for a project hosted on Google App Engine. Unfortunately, Google App Engine does not support the unsafe package.([link](https://blog.golang.org/go-and-google-app-engine))

Is it possible to refactor to not have to use the unsafe package? https://github.com/ikawaha/kagome/search?utf8=%E2%9C%93&q=unsafe

**Comment by ikawaha** [comment]
Using the `appengine` build tag, it is possible to split it into the app engine specific part and the other.  Is it ok?

**Comment by niconegoto** [comment]
Cool!!! 
Thank you for your quick response.

**Comment by ikawaha** [comment]
I do not have the GAE environment, please let me know if this works :), thank you.

**Comment by ikawaha** [comment]
Merged : https://github.com/ikawaha/kagome/tree/v1.6.0

**Comment by ikawaha** [comment]
Merged : https://github.com/ikawaha/kagome/releases/tag/v1.6.1

Even without the unsafe package, performance does not change so much.
In the future, the unsafe package and the appengine tag might be removed from kagome.

**Comment by ikawaha** [comment]
According to the report from @kaneshin =san, it could not upload kagome because of the file size limitation of the GAE.

```
2016-09-27 11:02:23,333 ERROR appcfg.py:2514 Ignoring file 'github.com/ikawaha/kagome/internal/dic/data/bindata09.go': Too long (max 32000000 bytes, file is 33301559 bytes). 
2016-09-27 11:02:23,350 ERROR appcfg.py:2514 Ignoring file 'github.com/ikawaha/kagome/internal/dic/data/bindata07.go': Too long (max 32000000 bytes, file is 102459182 bytes). 
2016-09-27 11:02:23,352 ERROR appcfg.py:2514 Ignoring file 'github.com/ikawaha/kagome/internal/dic/data/bindata08.go': Too long (max 32000000 bytes, file is 34556382 bytes). 
```

**Comment by ikawaha** [comment]
I backported from kagome to kagome.ipadic which is the small dictionary version of kagome, and fixed  it. So it is able to upload the kagome.ipadic to Google App Engine 

But some other reason, the tokenizer does  not run on GAE. 😩 
\# It runs on a local machine....

![image](https://cloud.githubusercontent.com/assets/4232165/19025659/db9f3ef6-8956-11e6-9337-fd53672de6b0.png)

**Comment by ikawaha** [comment]
📢  @kaneshin , @niconegoto 

By selecting the appropriate instance class (at least B8), kagome.ipadic runs on GAE.
Please use **[kagome.ipadic](https://github.com/ikawaha/kagome.ipadic)** for Google App Engine, thank you.

![image](https://cloud.githubusercontent.com/assets/4232165/19033178/1bbd8510-8998-11e6-82fd-78ac67edb759.png)

**Comment by ikawaha** [comment]
:octocat:  memo: http://ikawaha.hateblo.jp/entry/2016/10/04/221708
